// ============================================
// DASHBOARD - DADOS EDITAVEIS (Publicacoes)
// Gerado a partir de Publicacoes.xlsx
// ============================================

const data = [
  {"fornecedor":"Vonder","detalhe":"","logo":"Vonder.png","status":"Ativo","lote":"-","statusPublicacao":"Em produção","rk":1,"resp":"Lucas","listados":400,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Worker","detalhe":"","logo":"WORKER.png","status":"Ativo","lote":"5º","statusPublicacao":"Em produção","rk":2,"resp":"Lucas","listados":1500,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Beta","detalhe":"","logo":"Beta.png","status":"Ativo","lote":"2º","statusPublicacao":"Em produção","rk":3,"resp":"Lucas","listados":3000,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Tramomtina","detalhe":"Ferramentas","logo":"Tramontina.png","status":"Ativo","lote":"4º","statusPublicacao":"Em produção","rk":4,"resp":"Lucas","listados":3000,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Britania","detalhe":"","logo":"britania.png","status":"Ativo","lote":"6º","statusPublicacao":"Em produção","rk":1,"resp":"Lucas","listados":96,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Vonder","detalhe":"Kit","logo":"Vonder.png","status":"Ativo","lote":"1º","statusPublicacao":"Em produção","rk":1,"resp":"Lucas","listados":100,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Brinox","detalhe":"","logo":"brinox.png","status":"Novo","lote":"1º","statusPublicacao":"Em produção","rk":1,"resp":"Lucas","listados":600,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Bel","detalhe":"","logo":"Bel.png","status":"Ativo","lote":"8º","statusPublicacao":"Próximo da fila","rk":2,"resp":"Lucas","listados":450,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Wap","detalhe":"","logo":"Wap.png","status":"Ativo","lote":"9º","statusPublicacao":"Próximo da fila","rk":1,"resp":"Lucas","listados":220,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Makita","detalhe":"","logo":"Makita.png","status":"Ativo","lote":"9º","statusPublicacao":"Próximo da fila","rk":1,"resp":"Lucas","listados":0,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Bosch","detalhe":"","logo":"Bosch.png","status":"Ativo","lote":"2º","statusPublicacao":"Próximo da fila","rk":1,"resp":"Lucas","listados":1200,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Csm","detalhe":"","logo":"CSM.png","status":"Ativo","lote":"4º","statusPublicacao":"Próximo da fila","rk":3,"resp":"Jone","listados":75,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Branco","detalhe":"","logo":"Branco.png","status":"Ativo","lote":"2º","statusPublicacao":"Próximo da fila","rk":3,"resp":"Lucas","listados":250,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"KIAN","detalhe":"","logo":"Kian.png","status":"Novo","lote":"1º","statusPublicacao":"Próximo da fila","rk":3,"resp":"Lucas","listados":114,"scoreCross":0,"scoreEstoque":1,"resumo":""},
  {"fornecedor":"Gedore","detalhe":"","logo":"gedore.png","status":"","lote":"","statusPublicacao":"Em análise","rk":1,"resp":"sem responsável","listados":8500,"scoreCross":2,"scoreEstoque":1,"resumo":"Cadastros concluídos: 5.246 Blue, 773 Red e 136 Robust\nValidação da raspagem de descrições/técnicos em andamento\nSem API; estoque diário, preços mudam 1-2x por ano\nLimite de crédito pendente por apontamentos de impostos\nPedido mín. R$ 2 mil, frete CIF; 28/42/56 dias ou 3% à vista"},
  {"fornecedor":"Wolff + Lyor","detalhe":"","logo":"lyor.png","status":"","lote":"","statusPublicacao":"Em análise","rk":2,"resp":"sem responsável","listados":8500,"scoreCross":2,"scoreEstoque":2,"resumo":"Alinhando listagens e processos para fechar negócio"},
  {"fornecedor":"Elber Altomotive","detalhe":"","logo":"elber.png","status":"","lote":"","statusPublicacao":"Em análise","rk":3,"resp":"sem responsável","listados":23,"scoreCross":2,"scoreEstoque":3,"resumo":"API liberada e Cross Docking viável\nDados técnicos, descrições e imagens prontos\nFaturamento 30/60 dias, entrega em 2 a 3 dias\nEstoque monitorado semanalmente com alertas de saldo crítico\nFrete CIF em análise para redução de custo"},
  {"fornecedor":"Fischer","detalhe":"","logo":"fischer.png","status":"","lote":"","statusPublicacao":"Em análise","rk":4,"resp":"sem responsável","listados":180,"scoreCross":1,"scoreEstoque":2,"resumo":"Vendedor interno dedicado à conta de e-commerce\nCatálogo com ~200 produtos ativos e dados completos\nCross-docking estimado em 10 dias\nFrete FOB, pedido mín. R$ 5 mil (em renegociação)\nCrédito condicionado ao 1º pedido à vista"},
  {"fornecedor":"Kress + Wesco","detalhe":"","logo":"kress.png","status":"","lote":"","statusPublicacao":"Em análise","rk":3,"resp":"sem responsável","listados":350,"scoreCross":1,"scoreEstoque":2,"resumo":"Faturamento: análise de crédito simples, com possibilidade de 30/60/90 dias\nCIF de R$ 2.500\nEstoque: lista recorrente de itens esgotados; marca informa baixa ruptura\nCatálogo com menos de 400 SKUs em 3 marcas: Kress (premium), Wesco (entrada/hobby) e Worx (pouco trabalhada)\nDados de publicação em levantamento; peso e dimensões ainda pendentes\nLogística Campinas → Itajaí em ~7 dias; vão avaliar fluxo mais ágil para cross docking\nOportunidade: seríamos o 1º cliente em cross docking estruturado; marca quer ampliar vendas"},
  {"fornecedor":"Multi","detalhe":"","logo":"multi.png","status":"","lote":"","statusPublicacao":"Em análise","rk":3,"resp":"sem responsável","listados":7500,"scoreCross":0,"scoreEstoque":1,"resumo":"Faturamento mín. R$ 600, CIF a partir de R$ 1.200\nBoleto 6x, cartão 12x ou à vista com 2% de desconto\nEntrega Itajaí/Curitiba em 5 a 8 dias úteis\nPrioriza e-commerce direto e dificulta revendedores\nNão entrega em endereço diferente do CNPJ cadastrado\nAguarda painel B2B com API previsto para dez/2026"},
  {"fornecedor":"Amatools","detalhe":"","logo":"amatools.png","status":"","lote":"","statusPublicacao":"Em análise","rk":3,"resp":"sem responsável","listados":null,"scoreCross":1,"scoreEstoque":1,"resumo":"Mesmo representante da Gedore, projeto será iniciado após finalizar Gedore. "},
  {"fornecedor":"Menegotti","detalhe":"","logo":"Menegotti.png","status":"Reativando","lote":"4º","statusPublicacao":"Espera de Reativação","rk":4,"resp":"Lucas","listados":100,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Puma","detalhe":"","logo":"puma.png","status":"Reativando","lote":"2º","statusPublicacao":"Espera de Reativação","rk":2,"resp":"Lucas","listados":150,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"PDR","detalhe":"","logo":"PDR.png","status":"Reativando","lote":"2º","statusPublicacao":"Espera de Reativação","rk":1,"resp":"Lucas","listados":450,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Balmer","detalhe":"","logo":"Balmer.png","status":"Ativo","lote":"3º","statusPublicacao":"Indefinido","rk":4,"resp":"sem responsável","listados":0,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Chiaperini","detalhe":"","logo":"Chiaperini.png","status":"Ativo","lote":"2º","statusPublicacao":"Indefinido","rk":4,"resp":"sem responsável","listados":0,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Toyama","detalhe":"","logo":"Toyama.png","status":"Ativo","lote":"5º","statusPublicacao":"Indefinido","rk":1,"resp":"sem responsável","listados":0,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Buffalo","detalhe":"","logo":"Buffalo.png","status":"Ativo","lote":"3º","statusPublicacao":"Indefinido","rk":2,"resp":"sem responsável","listados":0,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"GMEG","detalhe":"","logo":"GMEG.png","status":"Ativo","lote":"2º","statusPublicacao":"Indefinido","rk":3,"resp":"sem responsável","listados":0,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Tekna","detalhe":"","logo":"Tekna.png","status":"Ativo","lote":"3º","statusPublicacao":"Indefinido","rk":4,"resp":"sem responsável","listados":0,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"Presto","detalhe":"","logo":"PRESTO.png","status":"Ativo","lote":"5º","statusPublicacao":"Indefinido","rk":3,"resp":"sem responsável","listados":0,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"BOVENAU","detalhe":"","logo":"BOVENAU.png","status":"Ativo","lote":"2º","statusPublicacao":"Indefinido","rk":3,"resp":"sem responsável","listados":0,"scoreCross":null,"scoreEstoque":null,"resumo":""},
  {"fornecedor":"CCM","detalhe":"","logo":"CCM.png","status":"Ativo","lote":"3º","statusPublicacao":"Indefinido","rk":3,"resp":"sem responsável","listados":0,"scoreCross":null,"scoreEstoque":null,"resumo":""}
];
