const marketplacesData = [
  {
    "ordem": 1,
    "image": "amazon.png",
    "canal": "AMAZON GUIMEPA",
    "comissaoBase": "11% a 14%",
    "faturamento": "TODAS",
    "nomeLoja": "Guimepa",
    "localEstoque": "GUIMEPA",
    "funcionamentoEstoque": "TODAS AS EMPRESAS",
    "sac": "Thais",
    "politicaCancelamento": "20% SOBRE A COMISSÃO DA CATEGORIA (INDEPENDENTE, EXCETO CANCELADO POR ELES)",
    "politicaFrete": "TABELA PRÓPRIA",
    "politicaRepasse": "Antecipado 30 dias",
    "disparoRepasse": "Entregue",
    "comissaoFrete": "SIM",
    "portador": "AMAZON GUIMEPA",
    "slaSac": "24 à 48 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "23.157.174/0001-68 - GMP",
    "cotaSku": "NÃO",
    "plataformaCotacao": "X",
    "canalIntelipost": "X",
    "idLoja": "A2U2MIP3BHAN9S",
    "validaXml": "Não Validam"
  },
  {
    "ordem": 2,
    "image": "leroy.png",
    "canal": "LEROY MERLIN",
    "comissaoBase": "18%",
    "faturamento": "TODAS",
    "nomeLoja": "Guimepa",
    "localEstoque": "GUIMEPA",
    "funcionamentoEstoque": "TODAS AS EMPRESAS",
    "sac": "Karin",
    "politicaCancelamento": "18% (QUANDO CANCELADO POR ERRO NOSSO) 13% DE TAXA POR ARREPENDIMENTO",
    "politicaFrete": "INTELIPOST",
    "politicaRepasse": "Antecipado",
    "disparoRepasse": "Entregue",
    "comissaoFrete": "SIM",
    "portador": "LEROY BOLETO / LEROY WIRECARD / LEROY PIX",
    "slaSac": "24 à 48 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "23.157.174/0001-68 - GMP",
    "cotaSku": "SIM",
    "plataformaCotacao": "LeroyMerlin",
    "canalIntelipost": "Vazio",
    "idLoja": "2338",
    "validaXml": "Não Validam"
  },
  {
    "ordem": 3,
    "image": "livelo.png",
    "canal": "LIVELO",
    "comissaoBase": "18%",
    "faturamento": "TODAS",
    "nomeLoja": "Guimepa",
    "localEstoque": "GUIMEPA",
    "funcionamentoEstoque": "TODAS AS EMPRESAS",
    "sac": "Thais",
    "politicaCancelamento": "18% INDEPENDENTE",
    "politicaFrete": "INTELIPOST",
    "politicaRepasse": "Fluxo",
    "disparoRepasse": "Faturado",
    "comissaoFrete": "SIM",
    "portador": "LIVELO",
    "slaSac": "24 à 48 horas úteis",
    "atendimentoSac": "Painel/E-mail",
    "cnpj": "39.590.561/0001-23 - GMK8",
    "cotaSku": "SIM",
    "plataformaCotacao": "anymarket",
    "canalIntelipost": "SHOPPING_LIVELO",
    "idLoja": "Não informado",
    "validaXml": "Não Validam"
  },
  {
    "ordem": 4,
    "image": "ll.png",
    "canal": "LL LOYALTY",
    "comissaoBase": "18%",
    "faturamento": "TODAS",
    "nomeLoja": "Guimepa",
    "localEstoque": "GUIMEPA",
    "funcionamentoEstoque": "TODAS AS EMPRESAS",
    "sac": "Thais",
    "politicaCancelamento": "Não cobra taxas",
    "politicaFrete": "INTELIPOST",
    "politicaRepasse": "Antecipado 45 dias",
    "disparoRepasse": "Faturado",
    "comissaoFrete": "SIM",
    "portador": "LL LOYALTY",
    "slaSac": "24 à 48 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "39.590.561/0001-23 - GMK8",
    "cotaSku": "NÃO",
    "plataformaCotacao": "anymarket",
    "canalIntelipost": "Não informado",
    "idLoja": "BRBRLCXHLLVA",
    "validaXml": "Não Validam"
  },
  {
    "ordem": 5,
    "image": "loja.png",
    "canal": "LOJA DO COOPERADO - SICOOB",
    "comissaoBase": "16%",
    "faturamento": "GMK8",
    "nomeLoja": "Guimepa",
    "localEstoque": "ESTOQUE SC",
    "funcionamentoEstoque": "TAB SC + LIQ SC",
    "sac": "Thais",
    "politicaCancelamento": "Não cobra taxas",
    "politicaFrete": "INTELIPOST",
    "politicaRepasse": "Antecipado 30 dias",
    "disparoRepasse": "Entregue",
    "comissaoFrete": "SIM",
    "portador": "SICOOB",
    "slaSac": "24 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "39.590.561/0001-23 - GMK8",
    "cotaSku": "NÃO",
    "plataformaCotacao": "anymarket",
    "canalIntelipost": "Não informado",
    "idLoja": "Não informado",
    "validaXml": "Não Validam"
  },
  {
    "ordem": 6,
    "image": "magalu.png",
    "canal": "MAGALU-GUIMEPA",
    "comissaoBase": "13%",
    "faturamento": "GMP",
    "nomeLoja": "Guimepa",
    "localEstoque": "ESTOQUE PR",
    "funcionamentoEstoque": "ESTOQUE PR + LIQ PR",
    "sac": "Karin",
    "politicaCancelamento": "6,5% (INDEPENDENTE) 18% (EXCESSÃO QUANDO AVARIA)",
    "politicaFrete": "INTELIPOST",
    "politicaRepasse": "Antecipado toda semana",
    "disparoRepasse": "Entregue",
    "comissaoFrete": "SIM",
    "portador": "MAGAZINE LUIZA GUIMEPA",
    "slaSac": "24 à 48 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "23.157.174/0001-68 - GMP",
    "cotaSku": "SIM",
    "plataformaCotacao": "integracommerce",
    "canalIntelipost": "Vazio",
    "idLoja": "Não informado",
    "validaXml": "Status Altera Por Xml"
  },
  {
    "ordem": 7,
    "image": "magalu.png",
    "canal": "MAGALU-GUIMEPA SHOP",
    "comissaoBase": "13%",
    "faturamento": "GMK8",
    "nomeLoja": "Guimepa Shop",
    "localEstoque": "ESTOQUE SC",
    "funcionamentoEstoque": "TAB SC + LIQ SC",
    "sac": "Karin",
    "politicaCancelamento": "6,5% (INDEPENDENTE) 18% (EXCESSÃO QUANDO AVARIA)",
    "politicaFrete": "INTELIPOST",
    "politicaRepasse": "Antecipado toda semana",
    "disparoRepasse": "Entregue",
    "comissaoFrete": "SIM",
    "portador": "MAGAZINE LUIZA GMK8",
    "slaSac": "48 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "39.590.561/0001-23 - GMK8",
    "cotaSku": "SIM",
    "plataformaCotacao": "integracommerce",
    "canalIntelipost": "Vazio",
    "idLoja": "Não informado",
    "validaXml": "Status Altera Por Xml"
  },
  {
    "ordem": 8,
    "image": "meli.png",
    "canal": "MELI DELTATOP",
    "comissaoBase": "12% Clá 17% Pre",
    "faturamento": "GMK8",
    "nomeLoja": "DeltatopFerramentas",
    "localEstoque": "ESTOQUE OVD GMK8",
    "funcionamentoEstoque": "TAB SC + LIQ SC + Cross 2",
    "sac": "Karin",
    "politicaCancelamento": "Não cobra taxas",
    "politicaFrete": "MERCADO ENVIOS",
    "politicaRepasse": "Saque",
    "disparoRepasse": "Saque",
    "comissaoFrete": "NÃO",
    "portador": "MERCADO LIVRE DELTATOP",
    "slaSac": "48 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "29.300.337/0001-04 - DELTATOP",
    "cotaSku": "SIM",
    "plataformaCotacao": "X",
    "canalIntelipost": "X",
    "idLoja": "Não informado",
    "validaXml": "Quando Mercado Envios"
  },
  {
    "ordem": 9,
    "image": "meli.png",
    "canal": "MELI GUIMEPA",
    "comissaoBase": "12% Clá 17% Pre",
    "faturamento": "TODAS",
    "nomeLoja": "Guimepa",
    "localEstoque": "GUIMEPA",
    "funcionamentoEstoque": "TODAS AS EMPRESAS",
    "sac": "Karin",
    "politicaCancelamento": "Não cobra taxas",
    "politicaFrete": "INTELIPOST + ME2",
    "politicaRepasse": "Saque",
    "disparoRepasse": "Saque",
    "comissaoFrete": "NÃO",
    "portador": "MERCADO LIVRE GMP",
    "slaSac": "48 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "39.590.561/0001-23 - GMK8",
    "cotaSku": "SIM",
    "plataformaCotacao": "anymarket",
    "canalIntelipost": "MERCADO_LIVRE",
    "idLoja": "206824173",
    "validaXml": "Quando Mercado Envios"
  },
  {
    "ordem": 10,
    "image": "meli.png",
    "canal": "MELI GUIMEPA SHOP",
    "comissaoBase": "12% Clá 17% Pre",
    "faturamento": "GMK8",
    "nomeLoja": "Guimepa Shop",
    "localEstoque": "ESTOQUE OVD GMK8",
    "funcionamentoEstoque": "TAB SC + LIQ SC + Cross 2",
    "sac": "Karin",
    "politicaCancelamento": "Não cobra taxas",
    "politicaFrete": "MERCADO ENVIOS",
    "politicaRepasse": "Saque",
    "disparoRepasse": "Saque",
    "comissaoFrete": "NÃO",
    "portador": "MERCADO_LIVRE-GUIMEPA-SC",
    "slaSac": "48 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "14.213.283/0002-45 - GUIMEPA SC",
    "cotaSku": "SIM",
    "plataformaCotacao": "X",
    "canalIntelipost": "X",
    "idLoja": "1399336189",
    "validaXml": "Quando Mercado Envios"
  },
  {
    "ordem": 11,
    "image": "meli.png",
    "canal": "MELI GUIMEPA STORE",
    "comissaoBase": "12% Clá 17% Pre",
    "faturamento": "GMK8",
    "nomeLoja": "Guimepa Store",
    "localEstoque": "ESTOQUE OVD GMK8",
    "funcionamentoEstoque": "TAB SC + LIQ SC + Cross 2",
    "sac": "Karin",
    "politicaCancelamento": "Não cobra taxas",
    "politicaFrete": "MERCADO ENVIOS",
    "politicaRepasse": "Saque",
    "disparoRepasse": "Saque",
    "comissaoFrete": "NÃO",
    "portador": "MERCADO_LIVRE-GUIMEPA-SC",
    "slaSac": "48 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "23.157.174/0001-68 - GMP",
    "cotaSku": "SIM",
    "plataformaCotacao": "X",
    "canalIntelipost": "X",
    "idLoja": "1399336189",
    "validaXml": "Quando Mercado Envios"
  },
  {
    "ordem": 12,
    "image": "senff.png",
    "canal": "SENFF",
    "comissaoBase": "14%",
    "faturamento": "TODAS",
    "nomeLoja": "Guimepa",
    "localEstoque": "GUIMEPA",
    "funcionamentoEstoque": "TODAS AS EMPRESAS",
    "sac": "Thais",
    "politicaCancelamento": "14% INDEPENDENTE",
    "politicaFrete": "INTELIPOST",
    "politicaRepasse": "Parcelado no Fluxo",
    "disparoRepasse": "Entregue",
    "comissaoFrete": "SIM",
    "portador": "SENFF",
    "slaSac": "24 à 48 horas úteis",
    "atendimentoSac": "E-mail",
    "cnpj": "39.590.561/0001-23 - GMK8",
    "cotaSku": "NÃO",
    "plataformaCotacao": "anymarket",
    "canalIntelipost": "Não informado",
    "idLoja": "Não informado",
    "validaXml": "Não Validam"
  },
  {
    "ordem": 13,
    "image": "shopee.png",
    "canal": "SHOPEE GUIMEPA",
    "comissaoBase": "18%",
    "faturamento": "TODAS",
    "nomeLoja": "Guimepa",
    "localEstoque": "ESTOQUE SC",
    "funcionamentoEstoque": "TAB SC + LIQ SC",
    "sac": "Thais",
    "politicaCancelamento": "Não cobra taxas",
    "politicaFrete": "INTELIPOST",
    "politicaRepasse": "Saque",
    "disparoRepasse": "Saque",
    "comissaoFrete": "NÃO",
    "portador": "SHOPEE GMK8",
    "slaSac": "48 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "39.590.561/0001-23 - GMK8",
    "cotaSku": "NÃO",
    "plataformaCotacao": "Shopee",
    "canalIntelipost": "Vazio",
    "idLoja": "11304810760",
    "validaXml": "Status Altera Por Xml"
  },
  {
    "ordem": 14,
    "image": "shopee.png",
    "canal": "SHOPEE GUIMEPA STORE",
    "comissaoBase": "18%",
    "faturamento": "GMK8",
    "nomeLoja": "Guimepa Store",
    "localEstoque": "ESTOQUE LIQ SC",
    "funcionamentoEstoque": "LIQ SC",
    "sac": "Thais",
    "politicaCancelamento": "Não cobra taxas",
    "politicaFrete": "SPX",
    "politicaRepasse": "Saque",
    "disparoRepasse": "Saque",
    "comissaoFrete": "NÃO",
    "portador": "SHOPEE GMK8",
    "slaSac": "48 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "14.213.283/0002-45 - GUIMEPA SC",
    "cotaSku": "NÃO",
    "plataformaCotacao": "Shopee",
    "canalIntelipost": "Vazio",
    "idLoja": "58207492242",
    "validaXml": "Status Altera Por Xml"
  },
  {
    "ordem": 15,
    "image": "shophub.png",
    "canal": "SHOPHUB",
    "comissaoBase": "15%",
    "faturamento": "TODAS",
    "nomeLoja": "Guimepa",
    "localEstoque": "GUIMEPA",
    "funcionamentoEstoque": "TODAS AS EMPRESAS",
    "sac": "Thais",
    "politicaCancelamento": "NÃO COBRA COMISSÃO DE PEDIDOS CANCELADOS, APENAS ENTREGUES",
    "politicaFrete": "INTELIPOST",
    "politicaRepasse": "Antecipado 30 dias",
    "disparoRepasse": "Entregue",
    "comissaoFrete": "NÃO",
    "portador": "SHOPHUB",
    "slaSac": "24 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "39.590.561/0001-23 - GMK8",
    "cotaSku": "SIM",
    "plataformaCotacao": "anymarket",
    "canalIntelipost": "SHOPHUB",
    "idLoja": "Não informado",
    "validaXml": "Não Validam"
  },
  {
    "ordem": 16,
    "image": "site.png",
    "canal": "SITE",
    "comissaoBase": "Por parcelamento",
    "faturamento": "TODAS",
    "nomeLoja": "Guimepa",
    "localEstoque": "GUIMEPA",
    "funcionamentoEstoque": "TODAS AS EMPRESAS",
    "sac": "Karin",
    "politicaCancelamento": "Não cobra taxas quando cancelado total, se estornado parcial, cobra a taxa no valor total",
    "politicaFrete": "INTELIPOST",
    "politicaRepasse": "Saque",
    "disparoRepasse": "Saque",
    "comissaoFrete": "SIM",
    "portador": "MERCADO SHOP SITE",
    "slaSac": "SEM PRAZO",
    "atendimentoSac": "E-mail",
    "cnpj": "23.157.174/0001-68 - GMP",
    "cotaSku": "SIM",
    "plataformaCotacao": "anymarket",
    "canalIntelipost": "Shopify",
    "idLoja": "Não informado",
    "validaXml": "Não Validam"
  },
  {
    "ordem": 17,
    "image": "tiktok.png",
    "canal": "TIKTOK SHOP",
    "comissaoBase": "6% + 8% Afiliado",
    "faturamento": "GMK8",
    "nomeLoja": "Guimepa",
    "localEstoque": "ESTOQUE SC",
    "funcionamentoEstoque": "TAB SC + LIQ SC",
    "sac": "Thais",
    "politicaCancelamento": "Não cobra taxas",
    "politicaFrete": "TIKTOK ENVIOS",
    "politicaRepasse": "Antecipado 30 dias",
    "disparoRepasse": "Entregue",
    "comissaoFrete": "NÃO",
    "portador": "TIKTOK SHOP",
    "slaSac": "24 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "39.590.561/0001-23 - GMK8",
    "cotaSku": "NÃO",
    "plataformaCotacao": "X",
    "canalIntelipost": "X",
    "idLoja": "Não informado",
    "validaXml": "Status Altera Por Xml"
  },
  {
    "ordem": 18,
    "image": "webcontinental.png",
    "canal": "WEBCONTINENTAL GUIMEPA SHOP",
    "comissaoBase": "19%",
    "faturamento": "GMK8",
    "nomeLoja": "Guimepa Shop",
    "localEstoque": "ESTOQUE SC",
    "funcionamentoEstoque": "TAB SC + LIQ SC",
    "sac": "Thais",
    "politicaCancelamento": "19% INDEPENDENTE",
    "politicaFrete": "INTELIPOST",
    "politicaRepasse": "Antecipado 30 dias",
    "disparoRepasse": "Entregue",
    "comissaoFrete": "SIM",
    "portador": "WEBCONTINENTAL",
    "slaSac": "48 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "39.590.561/0001-23 - GMK8",
    "cotaSku": "NÃO",
    "plataformaCotacao": "webcontinental",
    "canalIntelipost": "Vazio",
    "idLoja": "2721",
    "validaXml": "Não Validam"
  },
  {
    "ordem": 19,
    "image": "temu.png",
    "canal": "TEMU",
    "comissaoBase": "0%",
    "faturamento": "GMK8",
    "nomeLoja": "Guimepa",
    "localEstoque": "ESTOQUE LIQ SC",
    "funcionamentoEstoque": "LIQ SC",
    "sac": "Thais",
    "politicaCancelamento": "Não cobra taxas",
    "politicaFrete": "TEMU",
    "politicaRepasse": "Saque",
    "disparoRepasse": "Saque",
    "comissaoFrete": "NÃO",
    "portador": "TEMU",
    "slaSac": "24 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "39.590.561/0001-23 - GMK8",
    "cotaSku": "NÃO",
    "plataformaCotacao": "X",
    "canalIntelipost": "X",
    "idLoja": "635517740347822",
    "validaXml": "Status Altera Por Xml"
  },
  {
    "ordem": 20,
    "image": "picpay.png",
    "canal": "PICPAY SHOP",
    "comissaoBase": "16%",
    "faturamento": "GMK8",
    "nomeLoja": "Guimepa",
    "localEstoque": "ESTOQUE SC",
    "funcionamentoEstoque": "TAB SC + LIQ SC",
    "sac": "Thais",
    "politicaCancelamento": "Não cobra taxas",
    "politicaFrete": "INTELIPOST",
    "politicaRepasse": "Antecipado 30 dias",
    "disparoRepasse": "Entregue",
    "comissaoFrete": "SIM",
    "portador": "PICPAY",
    "slaSac": "24 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "39.590.561/0001-23 - GMK8",
    "cotaSku": "SIM",
    "plataformaCotacao": "anymarket",
    "canalIntelipost": "Não informado",
    "idLoja": "39590561000",
    "validaXml": "Não Validam"
  },
  {
    "ordem": 21,
    "image": "shein.png",
    "canal": "SHEIN",
    "comissaoBase": "18%",
    "faturamento": "GMK8",
    "nomeLoja": "Guimepa",
    "localEstoque": "ESTOQUE LIQ SC",
    "funcionamentoEstoque": "LIQ SC",
    "sac": "Thais",
    "politicaCancelamento": "Não cobra taxas",
    "politicaFrete": "Shein Entregas",
    "politicaRepasse": "Saque",
    "disparoRepasse": "Entregue",
    "comissaoFrete": "NÃO",
    "portador": "SHEIN",
    "slaSac": "24 à 48 horas úteis",
    "atendimentoSac": "Painel",
    "cnpj": "39.590.561/0001-23 - GMK8",
    "cotaSku": "NÃO",
    "plataformaCotacao": "X",
    "canalIntelipost": "X",
    "idLoja": "GS5419435",
    "validaXml": "Status Altera Por Xml"
  }
];
