const transportadorasData = [
  {
    "transportadora": "Magalog SC",
    "image": "magalog.png",
    "fatorCubagem": "167,00 kg/m³",
    "regioesAtendidas": "BRASIL TODO",
    "idHardness": 15511,
    "enviaXml": "NÃO",
    "perfilTransporte": "Máx 0,80 m até 30 kg",
    "importante": null,
    "somaLados": "200 cm",
    "executivoConta": "Daniele Dias",
    "celular": null,
    "emailComercial": "daniele.dias@magazineluiza.com.br",
    "atendimentoAuxiliar": null,
    "emailAuxiliar": null,
    "regrasReversa": "Não tem reversa",
    "reentrega": null,
    "acrescimoIntelipost": "Por estado",
    "politicaRessarcimento": "Depósito em conta, mediante relatório e geração de nota de débito",
    "ordem": 1
  },
  {
    "transportadora": "Magalog PR",
    "image": "magalog.png",
    "fatorCubagem": "167,00 kg/m³",
    "regioesAtendidas": "BRASIL TODO",
    "idHardness": 15554,
    "enviaXml": "NÃO",
    "perfilTransporte": "Máx 0,80 m até 30 kg",
    "importante": null,
    "somaLados": "200 cm",
    "executivoConta": "Daniele Dias",
    "celular": null,
    "emailComercial": "daniele.dias@magazineluiza.com.br",
    "atendimentoAuxiliar": null,
    "emailAuxiliar": null,
    "regrasReversa": "Não tem reversa",
    "reentrega": null,
    "acrescimoIntelipost": "Por estado",
    "politicaRessarcimento": "Depósito em conta, mediante relatório e geração de nota de débito",
    "ordem": 2
  },
  {
    "transportadora": "Loggi",
    "image": "loggi.png",
    "fatorCubagem": "167,00 kg/m³",
    "regioesAtendidas": "BRASIL TODO",
    "idHardness": 7884,
    "enviaXml": "NÃO",
    "perfilTransporte": "Máx 1,00 m até 30 kg",
    "importante": null,
    "somaLados": "200 cm",
    "executivoConta": "Aline Nunes",
    "celular": "11 91194-4783",
    "emailComercial": "aline.nunes@loggi.com",
    "atendimentoAuxiliar": "Ariane Freitas",
    "emailAuxiliar": "ariane.galdino@loggi.com",
    "regrasReversa": "Não tem reversa",
    "reentrega": "Isento até 3 tentativas",
    "acrescimoIntelipost": "Por estado",
    "politicaRessarcimento": "Desconto em fatura",
    "ordem": 3
  },
  {
    "transportadora": "Braspress",
    "image": "braspress.png",
    "fatorCubagem": "300,00 kg/m³",
    "regioesAtendidas": "BRASIL TODO",
    "idHardness": 2,
    "enviaXml": "SIM",
    "perfilTransporte": "Máx 1,20 m até 50 kg",
    "importante": null,
    "somaLados": "-",
    "executivoConta": "Mayana",
    "celular": "41 99286-6964",
    "emailComercial": "cwb.vendas02@braspress.com",
    "atendimentoAuxiliar": null,
    "emailAuxiliar": null,
    "regrasReversa": "Somente pedidos despachados por eles",
    "reentrega": "Taxa fixa de R$ 1,95",
    "acrescimoIntelipost": "Por estado",
    "politicaRessarcimento": "Desconto em fatura ou crédito em conta, mediante negociação",
    "ordem": 4
  },
  {
    "transportadora": "Rodonaves SC",
    "image": "rodonaves.png",
    "fatorCubagem": "250,00 kg/m³",
    "regioesAtendidas": "EXCETO NORDESTE",
    "idHardness": 1,
    "enviaXml": "NÃO",
    "perfilTransporte": "Todos os perfis",
    "importante": "NE e N: máx 120 kg 110 x 100 x 160 (AxLxC em cm)",
    "somaLados": "-",
    "executivoConta": "Heder",
    "celular": "47 8813-3496",
    "emailComercial": "heder.vendrame@rte.com.br",
    "atendimentoAuxiliar": "cotacao.226@rte.com.br",
    "emailAuxiliar": null,
    "regrasReversa": "Somente com termo de isenção",
    "reentrega": "50 % do frete de ida",
    "acrescimoIntelipost": "Por estado",
    "politicaRessarcimento": "Desconto em fatura ou crédito em conta, mediante negociação",
    "ordem": 5
  },
  {
    "transportadora": "Rodonaves PR",
    "image": "rodonaves.png",
    "fatorCubagem": "300,00 kg/m³",
    "regioesAtendidas": "EXCETO NORDESTE",
    "idHardness": 14,
    "enviaXml": "NÃO",
    "perfilTransporte": "Todos os perfis",
    "importante": "NE e N: máx 120 kg 110 x 100 x 160 (AxLxC em cm)",
    "somaLados": "-",
    "executivoConta": "Fernando",
    "celular": "41 9855-1533",
    "emailComercial": "taisa.cubis@rte.com.br",
    "atendimentoAuxiliar": "cotacao.226@rte.com.br",
    "emailAuxiliar": null,
    "regrasReversa": "Somente com termo de isenção",
    "reentrega": "50 % do frete de ida",
    "acrescimoIntelipost": "Por estado",
    "politicaRessarcimento": "Desconto em fatura ou crédito em conta, mediante negociação",
    "ordem": 6
  },
  {
    "transportadora": "Alfa SC",
    "image": "alfa.png",
    "fatorCubagem": "250,00 kg/m³",
    "regioesAtendidas": "EXCETO NORTE E NORDESTE",
    "idHardness": 396,
    "enviaXml": "SIM",
    "perfilTransporte": "Máx 2,20 m",
    "importante": null,
    "somaLados": "-",
    "executivoConta": "Taila",
    "celular": "47 8869-1698",
    "emailComercial": "taila.taciana@alfatransportes.com.br",
    "atendimentoAuxiliar": null,
    "emailAuxiliar": null,
    "regrasReversa": null,
    "reentrega": null,
    "acrescimoIntelipost": "Por estado",
    "politicaRessarcimento": null,
    "ordem": 7
  },
  {
    "transportadora": "RPJ",
    "image": "rpj.png",
    "fatorCubagem": "250,00 kg/m³",
    "regioesAtendidas": "NORTE E NORDESTE",
    "idHardness": 15587,
    "enviaXml": "SIM",
    "perfilTransporte": "Máx 2,50 m",
    "importante": null,
    "somaLados": "-",
    "executivoConta": "Bruno",
    "celular": "41 9812-0694",
    "emailComercial": "comercial@rpjtransportes.com.br",
    "atendimentoAuxiliar": null,
    "emailAuxiliar": null,
    "regrasReversa": null,
    "reentrega": null,
    "acrescimoIntelipost": "Por estado",
    "politicaRessarcimento": null,
    "ordem": 8
  },
  {
    "transportadora": "Tecmar SC",
    "image": "tecmar.png",
    "fatorCubagem": "300,00 kg/m³",
    "regioesAtendidas": "NORTE E NORDESTE",
    "idHardness": 391,
    "enviaXml": "NÃO",
    "perfilTransporte": "Máx 2,80 m",
    "importante": null,
    "somaLados": "-",
    "executivoConta": "Eliane",
    "celular": "41 8444-1480",
    "emailComercial": "eliane.bruder@tecmartransportes.com.br",
    "atendimentoAuxiliar": null,
    "emailAuxiliar": null,
    "regrasReversa": null,
    "reentrega": null,
    "acrescimoIntelipost": "Por estado",
    "politicaRessarcimento": "Desconto em fatura ou crédito em conta, mediante negociação",
    "ordem": 9
  }
];
